# Generated by Django 3.0.4 on 2022-07-14 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='顧客名')),
                ('customer_app_date', models.DateField(auto_now_add=True, verbose_name='登録日')),
            ],
            options={
                'verbose_name': '顧客',
                'verbose_name_plural': '顧客',
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_date', models.DateField(verbose_name='製造日')),
                ('production_volume', models.IntegerField(verbose_name='製造量(CS)')),
            ],
            options={
                'verbose_name': '製造履歴',
                'verbose_name_plural': '製造履歴',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products_name', models.CharField(max_length=50, verbose_name='商品名')),
                ('best_before_duration', models.IntegerField(verbose_name='賞味期間(日)')),
                ('product_app_date', models.DateField(auto_now_add=True, verbose_name='登録日')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(verbose_name='販売日')),
                ('sale_volume', models.IntegerField(verbose_name='販売量(CS)')),
                ('sale_price', models.IntegerField(verbose_name='販売額(円/CS)')),
                ('best_before_duration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='賞味期間', to='graph.Products')),
                ('customer_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='販売先', to='graph.Customer')),
                ('production_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.Production')),
                ('products_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='商品名', to='graph.Products')),
            ],
            options={
                'verbose_name': '販売履歴',
                'verbose_name_plural': '販売履歴',
                'ordering': ('-sale_date',),
            },
        ),
        migrations.AddField(
            model_name='production',
            name='products_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='商品', to='graph.Products'),
        ),
    ]
