# Generated by Django 3.0.4 on 2022-07-12 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_app_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_date', models.DateField()),
                ('production_volume', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products_name', models.CharField(max_length=50)),
                ('best_before_duration', models.IntegerField()),
                ('product_app_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_before_date', models.IntegerField()),
                ('sale_date', models.DateField()),
                ('sale_volume', models.IntegerField()),
                ('sale_price', models.IntegerField()),
                ('unit_price', models.IntegerField()),
                ('best_before_duration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_best_before_duration', to='register.Products')),
                ('customer_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='register.Customer')),
                ('production_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_production_date', to='register.Production')),
                ('products_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_products_name', to='register.Products')),
            ],
        ),
        migrations.AddField(
            model_name='production',
            name='products_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Products'),
        ),
    ]
