# Generated by Django 3.0.4 on 2022-07-12 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='best_before_date',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='unit_price',
        ),
    ]
