# Generated by Django 3.0.4 on 2022-07-19 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20220712_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': '顧客', 'verbose_name_plural': '顧客'},
        ),
        migrations.AlterModelOptions(
            name='production',
            options={'verbose_name': '製造履歴', 'verbose_name_plural': '製造履歴'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ('-sale_date',), 'verbose_name': '販売履歴', 'verbose_name_plural': '販売履歴'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_app_date',
            field=models.DateField(auto_now_add=True, verbose_name='登録日'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(max_length=100, verbose_name='顧客名'),
        ),
        migrations.AlterField(
            model_name='production',
            name='production_date',
            field=models.DateField(verbose_name='製造日'),
        ),
        migrations.AlterField(
            model_name='production',
            name='production_volume',
            field=models.IntegerField(verbose_name='製造量(CS)'),
        ),
        migrations.AlterField(
            model_name='production',
            name='products_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='商品', to='register.Products'),
        ),
        migrations.AlterField(
            model_name='products',
            name='best_before_duration',
            field=models.IntegerField(verbose_name='賞味期間(日)'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_app_date',
            field=models.DateField(auto_now_add=True, verbose_name='登録日'),
        ),
        migrations.AlterField(
            model_name='products',
            name='products_name',
            field=models.CharField(max_length=50, verbose_name='商品名'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='best_before_duration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='賞味期間', to='register.Products'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='販売先', to='register.Customer'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='production_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Production'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='products_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='商品名', to='register.Products'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateField(verbose_name='販売日'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_price',
            field=models.IntegerField(verbose_name='販売額(円/CS)'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_volume',
            field=models.IntegerField(verbose_name='販売量(CS)'),
        ),
    ]
